// Copyright (c) 2025 Antonin Stefanutti <antonin.stefanutti@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/astefanutti/kpu/pkg/apis/kpu/v1alpha1"
	kpuv1alpha1 "github.com/astefanutti/kpu/pkg/client/applyconfiguration/kpu/v1alpha1"
	typedkpuv1alpha1 "github.com/astefanutti/kpu/pkg/client/clientset/versioned/typed/kpu/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeComputes implements ComputeInterface
type fakeComputes struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Compute, *v1alpha1.ComputeList, *kpuv1alpha1.ComputeApplyConfiguration]
	Fake *FakeComputeV1alpha1
}

func newFakeComputes(fake *FakeComputeV1alpha1, namespace string) typedkpuv1alpha1.ComputeInterface {
	return &fakeComputes{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Compute, *v1alpha1.ComputeList, *kpuv1alpha1.ComputeApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("computes"),
			v1alpha1.SchemeGroupVersion.WithKind("Compute"),
			func() *v1alpha1.Compute { return &v1alpha1.Compute{} },
			func() *v1alpha1.ComputeList { return &v1alpha1.ComputeList{} },
			func(dst, src *v1alpha1.ComputeList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ComputeList) []*v1alpha1.Compute { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.ComputeList, items []*v1alpha1.Compute) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
