//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright (c) 2025 Antonin Stefanutti <antonin.stefanutti@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Compute{}, func(obj interface{}) { SetObjectDefaults_Compute(obj.(*Compute)) })
	scheme.AddTypeDefaultingFunc(&ComputeList{}, func(obj interface{}) { SetObjectDefaults_ComputeList(obj.(*ComputeList)) })
	return nil
}

func SetObjectDefaults_Compute(in *Compute) {
	for i := range in.Spec.Env {
		a := &in.Spec.Env[i]
		if a.ValueFrom != nil {
			if a.ValueFrom.FileKeyRef != nil {
				if a.ValueFrom.FileKeyRef.Optional == nil {
					var ptrVar1 bool = false
					a.ValueFrom.FileKeyRef.Optional = &ptrVar1
				}
			}
		}
	}
	if in.Spec.Override != nil {
		for i := range in.Spec.Override.Volumes {
			a := &in.Spec.Override.Volumes[i]
			if a.VolumeSource.ISCSI != nil {
				if a.VolumeSource.ISCSI.ISCSIInterface == "" {
					a.VolumeSource.ISCSI.ISCSIInterface = "default"
				}
			}
			if a.VolumeSource.RBD != nil {
				if a.VolumeSource.RBD.RBDPool == "" {
					a.VolumeSource.RBD.RBDPool = "rbd"
				}
				if a.VolumeSource.RBD.RadosUser == "" {
					a.VolumeSource.RBD.RadosUser = "admin"
				}
				if a.VolumeSource.RBD.Keyring == "" {
					a.VolumeSource.RBD.Keyring = "/etc/ceph/keyring"
				}
			}
			if a.VolumeSource.AzureDisk != nil {
				if a.VolumeSource.AzureDisk.CachingMode == nil {
					ptrVar1 := v1.AzureDataDiskCachingMode(v1.AzureDataDiskCachingReadWrite)
					a.VolumeSource.AzureDisk.CachingMode = &ptrVar1
				}
				if a.VolumeSource.AzureDisk.FSType == nil {
					var ptrVar1 string = "ext4"
					a.VolumeSource.AzureDisk.FSType = &ptrVar1
				}
				if a.VolumeSource.AzureDisk.ReadOnly == nil {
					var ptrVar1 bool = false
					a.VolumeSource.AzureDisk.ReadOnly = &ptrVar1
				}
				if a.VolumeSource.AzureDisk.Kind == nil {
					ptrVar1 := v1.AzureDataDiskKind(v1.AzureSharedBlobDisk)
					a.VolumeSource.AzureDisk.Kind = &ptrVar1
				}
			}
			if a.VolumeSource.ScaleIO != nil {
				if a.VolumeSource.ScaleIO.StorageMode == "" {
					a.VolumeSource.ScaleIO.StorageMode = "ThinProvisioned"
				}
				if a.VolumeSource.ScaleIO.FSType == "" {
					a.VolumeSource.ScaleIO.FSType = "xfs"
				}
			}
		}
		for i := range in.Spec.Override.InitContainers {
			a := &in.Spec.Override.InitContainers[i]
			for j := range a.Env {
				b := &a.Env[j]
				if b.ValueFrom != nil {
					if b.ValueFrom.FileKeyRef != nil {
						if b.ValueFrom.FileKeyRef.Optional == nil {
							var ptrVar1 bool = false
							b.ValueFrom.FileKeyRef.Optional = &ptrVar1
						}
					}
				}
			}
		}
		for i := range in.Spec.Override.Containers {
			a := &in.Spec.Override.Containers[i]
			for j := range a.Env {
				b := &a.Env[j]
				if b.ValueFrom != nil {
					if b.ValueFrom.FileKeyRef != nil {
						if b.ValueFrom.FileKeyRef.Optional == nil {
							var ptrVar1 bool = false
							b.ValueFrom.FileKeyRef.Optional = &ptrVar1
						}
					}
				}
			}
		}
	}
}

func SetObjectDefaults_ComputeList(in *ComputeList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Compute(a)
	}
}
