// Copyright (c) 2025 Antonin Stefanutti <antonin.stefanutti@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	kpuv1alpha1 "github.com/astefanutti/kpu/pkg/apis/kpu/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ComputeLister helps list Computes.
// All objects returned here must be treated as read-only.
type ComputeLister interface {
	// List lists all Computes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kpuv1alpha1.Compute, err error)
	// Computes returns an object that can list and get Computes.
	Computes(namespace string) ComputeNamespaceLister
	ComputeListerExpansion
}

// computeLister implements the ComputeLister interface.
type computeLister struct {
	listers.ResourceIndexer[*kpuv1alpha1.Compute]
}

// NewComputeLister returns a new ComputeLister.
func NewComputeLister(indexer cache.Indexer) ComputeLister {
	return &computeLister{listers.New[*kpuv1alpha1.Compute](indexer, kpuv1alpha1.Resource("compute"))}
}

// Computes returns an object that can list and get Computes.
func (s *computeLister) Computes(namespace string) ComputeNamespaceLister {
	return computeNamespaceLister{listers.NewNamespaced[*kpuv1alpha1.Compute](s.ResourceIndexer, namespace)}
}

// ComputeNamespaceLister helps list and get Computes.
// All objects returned here must be treated as read-only.
type ComputeNamespaceLister interface {
	// List lists all Computes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kpuv1alpha1.Compute, err error)
	// Get retrieves the Compute from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kpuv1alpha1.Compute, error)
	ComputeNamespaceListerExpansion
}

// computeNamespaceLister implements the ComputeNamespaceLister
// interface.
type computeNamespaceLister struct {
	listers.ResourceIndexer[*kpuv1alpha1.Compute]
}
