// Copyright (c) 2025 Antonin Stefanutti <antonin.stefanutti@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// ComputeSpecApplyConfiguration represents a declarative configuration of the ComputeSpec type for use
// with apply.
type ComputeSpecApplyConfiguration struct {
	Labels      map[string]string             `json:"labels,omitempty"`
	Annotations map[string]string             `json:"annotations,omitempty"`
	Suspend     *bool                         `json:"suspend,omitempty"`
	Image       *string                       `json:"image,omitempty"`
	Command     []string                      `json:"command,omitempty"`
	Args        []string                      `json:"args,omitempty"`
	Env         []v1.EnvVarApplyConfiguration `json:"env,omitempty"`
	Resources   *corev1.ResourceList          `json:"resources,omitempty"`
}

// ComputeSpecApplyConfiguration constructs a declarative configuration of the ComputeSpec type for use with
// apply.
func ComputeSpec() *ComputeSpecApplyConfiguration {
	return &ComputeSpecApplyConfiguration{}
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ComputeSpecApplyConfiguration) WithLabels(entries map[string]string) *ComputeSpecApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ComputeSpecApplyConfiguration) WithAnnotations(entries map[string]string) *ComputeSpecApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *ComputeSpecApplyConfiguration) WithSuspend(value bool) *ComputeSpecApplyConfiguration {
	b.Suspend = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ComputeSpecApplyConfiguration) WithImage(value string) *ComputeSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithCommand adds the given value to the Command field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Command field.
func (b *ComputeSpecApplyConfiguration) WithCommand(values ...string) *ComputeSpecApplyConfiguration {
	for i := range values {
		b.Command = append(b.Command, values[i])
	}
	return b
}

// WithArgs adds the given value to the Args field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Args field.
func (b *ComputeSpecApplyConfiguration) WithArgs(values ...string) *ComputeSpecApplyConfiguration {
	for i := range values {
		b.Args = append(b.Args, values[i])
	}
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *ComputeSpecApplyConfiguration) WithEnv(values ...*v1.EnvVarApplyConfiguration) *ComputeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnv")
		}
		b.Env = append(b.Env, *values[i])
	}
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *ComputeSpecApplyConfiguration) WithResources(value corev1.ResourceList) *ComputeSpecApplyConfiguration {
	b.Resources = &value
	return b
}
