# coding: utf-8

"""
    KPU OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from client.models.io_k8s_api_core_v1_env_var import IoK8sApiCoreV1EnvVar
from typing import Optional, Set
from typing_extensions import Self

class KpuV1alpha1ComputeSpec(BaseModel):
    """
    ComputeSpec represents the specification of the Compute.
    """ # noqa: E501
    annotations: Optional[Dict[str, StrictStr]] = Field(default=None, description="annotations to apply to the Compute resources.")
    args: Optional[List[StrictStr]] = Field(default=None, description="args for the entrypoint for the Compute runtime.")
    command: Optional[List[StrictStr]] = Field(default=None, description="command for the entrypoint of the Compute runtime.")
    env: Optional[List[IoK8sApiCoreV1EnvVar]] = Field(default=None, description="env is the list of environment variables to set in the Compute runtime.")
    image: Optional[StrictStr] = Field(default=None, description="image is the container image for the Compute runtime.")
    labels: Optional[Dict[str, StrictStr]] = Field(default=None, description="labels to apply to the Compute resources.")
    suspend: Optional[StrictBool] = Field(default=None, description="suspend defines whether to suspend the running Compute. Defaults to false.")
    __properties: ClassVar[List[str]] = ["annotations", "args", "command", "env", "image", "labels", "suspend"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KpuV1alpha1ComputeSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in env (list)
        _items = []
        if self.env:
            for _item_env in self.env:
                if _item_env:
                    _items.append(_item_env.to_dict())
            _dict['env'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KpuV1alpha1ComputeSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "annotations": obj.get("annotations"),
            "args": obj.get("args"),
            "command": obj.get("command"),
            "env": [IoK8sApiCoreV1EnvVar.from_dict(_item) for _item in obj["env"]] if obj.get("env") is not None else None,
            "image": obj.get("image"),
            "labels": obj.get("labels"),
            "suspend": obj.get("suspend")
        })
        return _obj


