"""Generated ATen operator registrations for SkyTorch backend.

This file is auto-generated by hack/gen-aten-ops.py.
Do not edit manually.
"""

from typing import Any, Callable

import torch

from .dispatch import _sky_kernel_fallback


def _sky_kernel_fallback_wrapper(
    op: torch._ops.OpOverload | torch._ops.OpOverloadPacket,
) -> Callable[..., Any]:
    """Create a wrapper that calls _sky_kernel_fallback with the specified op."""

    def wrapper(*args: Any, **kwargs: Any) -> Any:
        return _sky_kernel_fallback(op, *args, **kwargs)

    return wrapper


# Register operators with sky backend
_sky_lib_aten = torch.library.Library("aten", "IMPL")

_sky_lib_aten.impl(
    "_adaptive_avg_pool2d",
    _sky_kernel_fallback_wrapper(torch.ops.aten._adaptive_avg_pool2d.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_adaptive_avg_pool2d.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten._adaptive_avg_pool2d.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_adaptive_avg_pool2d_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten._adaptive_avg_pool2d_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_adaptive_avg_pool2d_backward.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten._adaptive_avg_pool2d_backward.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_log_softmax",
    _sky_kernel_fallback_wrapper(torch.ops.aten._log_softmax.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_log_softmax.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten._log_softmax.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_log_softmax_backward_data",
    _sky_kernel_fallback_wrapper(torch.ops.aten._log_softmax_backward_data.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_log_softmax_backward_data.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten._log_softmax_backward_data.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_native_batch_norm_legit",
    _sky_kernel_fallback_wrapper(torch.ops.aten._native_batch_norm_legit.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_native_batch_norm_legit.no_stats",
    _sky_kernel_fallback_wrapper(torch.ops.aten._native_batch_norm_legit.no_stats),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_native_batch_norm_legit.no_stats_out",
    _sky_kernel_fallback_wrapper(torch.ops.aten._native_batch_norm_legit.no_stats_out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_native_batch_norm_legit.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten._native_batch_norm_legit.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_native_batch_norm_legit_no_training",
    _sky_kernel_fallback_wrapper(torch.ops.aten._native_batch_norm_legit_no_training.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_native_batch_norm_legit_no_training.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten._native_batch_norm_legit_no_training.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_softmax",
    _sky_kernel_fallback_wrapper(torch.ops.aten._softmax.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_softmax.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten._softmax.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_softmax_backward_data",
    _sky_kernel_fallback_wrapper(torch.ops.aten._softmax_backward_data.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "_softmax_backward_data.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten._softmax_backward_data.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "abs",
    _sky_kernel_fallback_wrapper(torch.ops.aten.abs.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "abs.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.abs.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "abs_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.abs_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "add.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.add.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "add.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.add.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "add.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.add.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "add_.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.add_.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "add_.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.add_.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "addmm",
    _sky_kernel_fallback_wrapper(torch.ops.aten.addmm.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "addmm.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.addmm.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "addmm_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.addmm_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "arange",
    _sky_kernel_fallback_wrapper(torch.ops.aten.arange.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "arange.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.arange.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "arange.start",
    _sky_kernel_fallback_wrapper(torch.ops.aten.arange.start),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "arange.start_out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.arange.start_out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "arange.start_step",
    _sky_kernel_fallback_wrapper(torch.ops.aten.arange.start_step),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "argmax",
    _sky_kernel_fallback_wrapper(torch.ops.aten.argmax.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "argmax.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.argmax.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "avg_pool2d",
    _sky_kernel_fallback_wrapper(torch.ops.aten.avg_pool2d.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "avg_pool2d.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.avg_pool2d.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "avg_pool2d_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.avg_pool2d_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "avg_pool2d_backward.grad_input",
    _sky_kernel_fallback_wrapper(torch.ops.aten.avg_pool2d_backward.grad_input),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "bmm",
    _sky_kernel_fallback_wrapper(torch.ops.aten.bmm.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "bmm.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.bmm.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "cat",
    _sky_kernel_fallback_wrapper(torch.ops.aten.cat.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "cat.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.cat.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "clone",
    _sky_kernel_fallback_wrapper(torch.ops.aten.clone.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "convolution",
    _sky_kernel_fallback_wrapper(torch.ops.aten.convolution.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "convolution.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.convolution.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "convolution_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.convolution_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "convolution_backward.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.convolution_backward.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "cos",
    _sky_kernel_fallback_wrapper(torch.ops.aten.cos.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "cos.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.cos.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "cumsum",
    _sky_kernel_fallback_wrapper(torch.ops.aten.cumsum.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "cumsum.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.cumsum.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "div.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.div.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "div.Scalar_mode",
    _sky_kernel_fallback_wrapper(torch.ops.aten.div.Scalar_mode),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "div.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.div.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "div.Tensor_mode",
    _sky_kernel_fallback_wrapper(torch.ops.aten.div.Tensor_mode),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "div.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.div.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "div_.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.div_.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "div_.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.div_.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "embedding",
    _sky_kernel_fallback_wrapper(torch.ops.aten.embedding.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "embedding_dense_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.embedding_dense_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "eq.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.eq.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "eq.Scalar_out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.eq.Scalar_out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "eq.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.eq.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "eq.Tensor_out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.eq.Tensor_out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "exp",
    _sky_kernel_fallback_wrapper(torch.ops.aten.exp.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "exp.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.exp.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "exp_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.exp_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "fill_.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.fill_.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "fill_.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.fill_.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "full",
    _sky_kernel_fallback_wrapper(torch.ops.aten.full.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "full.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.full.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "full_like",
    _sky_kernel_fallback_wrapper(torch.ops.aten.full_like.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "gather",
    _sky_kernel_fallback_wrapper(torch.ops.aten.gather.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "gather.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.gather.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "ge.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.ge.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "ge.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.ge.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "gelu",
    _sky_kernel_fallback_wrapper(torch.ops.aten.gelu.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "gelu.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.gelu.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "gelu_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.gelu_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "gelu_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.gelu_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "gelu_backward.grad_input",
    _sky_kernel_fallback_wrapper(torch.ops.aten.gelu_backward.grad_input),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "gt.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.gt.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "gt.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.gt.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "index.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.index.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "index.Tensor_out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.index.Tensor_out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "index_put",
    _sky_kernel_fallback_wrapper(torch.ops.aten.index_put.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "index_put_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.index_put_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "isinf",
    _sky_kernel_fallback_wrapper(torch.ops.aten.isinf.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "isinf.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.isinf.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "le.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.le.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "le.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.le.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "log",
    _sky_kernel_fallback_wrapper(torch.ops.aten.log.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "log.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.log.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "log_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.log_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "logical_and",
    _sky_kernel_fallback_wrapper(torch.ops.aten.logical_and.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "logical_and.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.logical_and.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "logical_and_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.logical_and_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "logical_not",
    _sky_kernel_fallback_wrapper(torch.ops.aten.logical_not.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "logical_not.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.logical_not.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "logical_not_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.logical_not_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "logical_or",
    _sky_kernel_fallback_wrapper(torch.ops.aten.logical_or.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "logical_or.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.logical_or.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "logical_or_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.logical_or_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "lt.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.lt.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "lt.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.lt.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "masked_fill.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.masked_fill.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "masked_fill.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.masked_fill.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "masked_fill_.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.masked_fill_.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "masked_fill_.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.masked_fill_.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "max",
    _sky_kernel_fallback_wrapper(torch.ops.aten.max.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "max.dim",
    _sky_kernel_fallback_wrapper(torch.ops.aten.max.dim),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "max.dim_max",
    _sky_kernel_fallback_wrapper(torch.ops.aten.max.dim_max),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "max_pool2d_with_indices",
    _sky_kernel_fallback_wrapper(torch.ops.aten.max_pool2d_with_indices.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "max_pool2d_with_indices.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.max_pool2d_with_indices.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "max_pool2d_with_indices_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.max_pool2d_with_indices_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "max_pool2d_with_indices_backward.grad_input",
    _sky_kernel_fallback_wrapper(torch.ops.aten.max_pool2d_with_indices_backward.grad_input),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "mean",
    _sky_kernel_fallback_wrapper(torch.ops.aten.mean.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "mean.dim",
    _sky_kernel_fallback_wrapper(torch.ops.aten.mean.dim),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "mean.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.mean.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "min",
    _sky_kernel_fallback_wrapper(torch.ops.aten.min.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "min.dim",
    _sky_kernel_fallback_wrapper(torch.ops.aten.min.dim),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "min.dim_min",
    _sky_kernel_fallback_wrapper(torch.ops.aten.min.dim_min),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "mm",
    _sky_kernel_fallback_wrapper(torch.ops.aten.mm.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "mm.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.mm.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "mul.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.mul.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "mul.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.mul.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "mul.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.mul.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "mul_.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.mul_.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "mul_.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.mul_.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "multinomial",
    _sky_kernel_fallback_wrapper(torch.ops.aten.multinomial.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "multinomial.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.multinomial.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "native_batch_norm_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.native_batch_norm_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "native_dropout.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.native_dropout.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "native_dropout_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.native_dropout_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "native_dropout_backward.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.native_dropout_backward.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "ne.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.ne.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "ne.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.ne.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "neg",
    _sky_kernel_fallback_wrapper(torch.ops.aten.neg.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "neg.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.neg.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "neg_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.neg_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "nll_loss2d_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.nll_loss2d_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "nll_loss2d_backward.grad_input",
    _sky_kernel_fallback_wrapper(torch.ops.aten.nll_loss2d_backward.grad_input),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "nll_loss2d_forward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.nll_loss2d_forward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "nll_loss2d_forward.output",
    _sky_kernel_fallback_wrapper(torch.ops.aten.nll_loss2d_forward.output),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "nll_loss_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.nll_loss_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "nll_loss_backward.grad_input",
    _sky_kernel_fallback_wrapper(torch.ops.aten.nll_loss_backward.grad_input),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "nll_loss_forward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.nll_loss_forward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "nll_loss_forward.output",
    _sky_kernel_fallback_wrapper(torch.ops.aten.nll_loss_forward.output),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "ones",
    _sky_kernel_fallback_wrapper(torch.ops.aten.ones.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "ones.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.ones.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "ones_like",
    _sky_kernel_fallback_wrapper(torch.ops.aten.ones_like.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "pow.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.pow.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "pow.Scalar_out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.pow.Scalar_out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "pow.Tensor_Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.pow.Tensor_Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "pow.Tensor_Scalar_out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.pow.Tensor_Scalar_out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "pow.Tensor_Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.pow.Tensor_Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "pow.Tensor_Tensor_out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.pow.Tensor_Tensor_out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "pow_.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.pow_.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "prod",
    _sky_kernel_fallback_wrapper(torch.ops.aten.prod.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "prod.dim_int",
    _sky_kernel_fallback_wrapper(torch.ops.aten.prod.dim_int),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "prod.int_out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.prod.int_out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "relu",
    _sky_kernel_fallback_wrapper(torch.ops.aten.relu.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "relu.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.relu.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "relu_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.relu_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "repeat_interleave.self_int",
    _sky_kernel_fallback_wrapper(torch.ops.aten.repeat_interleave.self_int),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "rsqrt",
    _sky_kernel_fallback_wrapper(torch.ops.aten.rsqrt.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "rsqrt.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.rsqrt.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "rsqrt_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.rsqrt_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "scalar_tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.scalar_tensor.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "scalar_tensor.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.scalar_tensor.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "scatter.src",
    _sky_kernel_fallback_wrapper(torch.ops.aten.scatter.src),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "scatter.value",
    _sky_kernel_fallback_wrapper(torch.ops.aten.scatter.value),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "scatter_.src",
    _sky_kernel_fallback_wrapper(torch.ops.aten.scatter_.src),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "scatter_.value",
    _sky_kernel_fallback_wrapper(torch.ops.aten.scatter_.value),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "scatter_add",
    _sky_kernel_fallback_wrapper(torch.ops.aten.scatter_add.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "scatter_add.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.scatter_add.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "scatter_add_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.scatter_add_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sigmoid",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sigmoid.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sigmoid.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sigmoid.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sigmoid_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sigmoid_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sigmoid_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sigmoid_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sigmoid_backward.grad_input",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sigmoid_backward.grad_input),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "silu",
    _sky_kernel_fallback_wrapper(torch.ops.aten.silu.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "silu.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.silu.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "silu_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.silu_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "silu_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.silu_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "silu_backward.grad_input",
    _sky_kernel_fallback_wrapper(torch.ops.aten.silu_backward.grad_input),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sin",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sin.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sin.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sin.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sort",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sort.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sort.values",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sort.values),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sort.values_stable",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sort.values_stable),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sqrt",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sqrt.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sqrt.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sqrt.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sqrt_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sqrt_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "stack",
    _sky_kernel_fallback_wrapper(torch.ops.aten.stack.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "stack.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.stack.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sub.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sub.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sub.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sub.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sub.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sub.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sub_.Scalar",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sub_.Scalar),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sub_.Tensor",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sub_.Tensor),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sum",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sum.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sum.dim_IntList",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sum.dim_IntList),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "sum.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.sum.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "tanh",
    _sky_kernel_fallback_wrapper(torch.ops.aten.tanh.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "tanh.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.tanh.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "tanh_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.tanh_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "tanh_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.tanh_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "tanh_backward.grad_input",
    _sky_kernel_fallback_wrapper(torch.ops.aten.tanh_backward.grad_input),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "threshold_backward",
    _sky_kernel_fallback_wrapper(torch.ops.aten.threshold_backward.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "threshold_backward.grad_input",
    _sky_kernel_fallback_wrapper(torch.ops.aten.threshold_backward.grad_input),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "topk",
    _sky_kernel_fallback_wrapper(torch.ops.aten.topk.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "topk.values",
    _sky_kernel_fallback_wrapper(torch.ops.aten.topk.values),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "tril",
    _sky_kernel_fallback_wrapper(torch.ops.aten.tril.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "tril.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.tril.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "triu",
    _sky_kernel_fallback_wrapper(torch.ops.aten.triu.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "triu.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.triu.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "where.self",
    _sky_kernel_fallback_wrapper(torch.ops.aten.where.self),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "where.self_out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.where.self_out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "zero_",
    _sky_kernel_fallback_wrapper(torch.ops.aten.zero_.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "zeros",
    _sky_kernel_fallback_wrapper(torch.ops.aten.zeros.default),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "zeros.out",
    _sky_kernel_fallback_wrapper(torch.ops.aten.zeros.out),
    dispatch_key="PrivateUse1",
)

_sky_lib_aten.impl(
    "zeros_like",
    _sky_kernel_fallback_wrapper(torch.ops.aten.zeros_like.default),
    dispatch_key="PrivateUse1",
)
