# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kpu/torch/server/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kpu/torch/server/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ekpu/torch/server/service.proto\x12\tkpu.torch\"\xd4\x01\n\x0bTensorChunk\x12\x11\n\ttensor_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63hunk_number\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x14\n\x0ctotal_chunks\x18\x04 \x01(\r\x12\x0f\n\x07is_last\x18\x05 \x01(\x08\x12\x36\n\x08metadata\x18\x06 \x03(\x0b\x32$.kpu.torch.TensorChunk.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"O\n\x0eTensorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1b\n\x13received_tensor_ids\x18\x03 \x03(\t\"\x8f\x01\n\rTensorRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12<\n\nparameters\x18\x02 \x03(\x0b\x32(.kpu.torch.TensorRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xd8\x01\n\x07Service\x12\x45\n\x0eReceiveTensors\x12\x16.kpu.torch.TensorChunk\x1a\x19.kpu.torch.TensorResponse(\x01\x12\x41\n\x0bSendTensors\x12\x18.kpu.torch.TensorRequest\x1a\x16.kpu.torch.TensorChunk0\x01\x12\x43\n\rStreamTensors\x12\x16.kpu.torch.TensorChunk\x1a\x16.kpu.torch.TensorChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kpu.torch.server.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORCHUNK_METADATAENTRY']._loaded_options = None
  _globals['_TENSORCHUNK_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_TENSORREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_TENSORREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_TENSORCHUNK']._serialized_start=46
  _globals['_TENSORCHUNK']._serialized_end=258
  _globals['_TENSORCHUNK_METADATAENTRY']._serialized_start=211
  _globals['_TENSORCHUNK_METADATAENTRY']._serialized_end=258
  _globals['_TENSORRESPONSE']._serialized_start=260
  _globals['_TENSORRESPONSE']._serialized_end=339
  _globals['_TENSORREQUEST']._serialized_start=342
  _globals['_TENSORREQUEST']._serialized_end=485
  _globals['_TENSORREQUEST_PARAMETERSENTRY']._serialized_start=436
  _globals['_TENSORREQUEST_PARAMETERSENTRY']._serialized_end=485
  _globals['_SERVICE']._serialized_start=488
  _globals['_SERVICE']._serialized_end=704
# @@protoc_insertion_point(module_scope)
