# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kpu.torch.server import service_pb2 as kpu_dot_torch_dot_server_dot_service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kpu/torch/server/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceStub(object):
    """Generic service for streaming PyTorch tensors between client and server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveTensors = channel.stream_unary(
                '/kpu.torch.Service/ReceiveTensors',
                request_serializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.SerializeToString,
                response_deserializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorResponse.FromString,
                _registered_method=True)
        self.SendTensors = channel.unary_stream(
                '/kpu.torch.Service/SendTensors',
                request_serializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorRequest.SerializeToString,
                response_deserializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.FromString,
                _registered_method=True)
        self.StreamTensors = channel.stream_stream(
                '/kpu.torch.Service/StreamTensors',
                request_serializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.SerializeToString,
                response_deserializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.FromString,
                _registered_method=True)


class ServiceServicer(object):
    """Generic service for streaming PyTorch tensors between client and server
    """

    def ReceiveTensors(self, request_iterator, context):
        """Client-to-server streaming: receive tensors from client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTensors(self, request, context):
        """Server-to-client streaming: send tensors to client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTensors(self, request_iterator, context):
        """Bidirectional streaming: send and receive tensors simultaneously
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveTensors': grpc.stream_unary_rpc_method_handler(
                    servicer.ReceiveTensors,
                    request_deserializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.FromString,
                    response_serializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorResponse.SerializeToString,
            ),
            'SendTensors': grpc.unary_stream_rpc_method_handler(
                    servicer.SendTensors,
                    request_deserializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorRequest.FromString,
                    response_serializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.SerializeToString,
            ),
            'StreamTensors': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTensors,
                    request_deserializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.FromString,
                    response_serializer=kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kpu.torch.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kpu.torch.Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Generic service for streaming PyTorch tensors between client and server
    """

    @staticmethod
    def ReceiveTensors(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kpu.torch.Service/ReceiveTensors',
            kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.SerializeToString,
            kpu_dot_torch_dot_server_dot_service__pb2.TensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kpu.torch.Service/SendTensors',
            kpu_dot_torch_dot_server_dot_service__pb2.TensorRequest.SerializeToString,
            kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTensors(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kpu.torch.Service/StreamTensors',
            kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.SerializeToString,
            kpu_dot_torch_dot_server_dot_service__pb2.TensorChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
