// Copyright (c) 2025 Antonin Stefanutti <antonin.stefanutti@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	computev1alpha1 "github.com/astefanutti/skytorch/pkg/apis/compute/v1alpha1"
	applyconfigurationcomputev1alpha1 "github.com/astefanutti/skytorch/pkg/client/applyconfiguration/compute/v1alpha1"
	scheme "github.com/astefanutti/skytorch/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ComputesGetter has a method to return a ComputeInterface.
// A group's client should implement this interface.
type ComputesGetter interface {
	Computes(namespace string) ComputeInterface
}

// ComputeInterface has methods to work with Compute resources.
type ComputeInterface interface {
	Create(ctx context.Context, compute *computev1alpha1.Compute, opts v1.CreateOptions) (*computev1alpha1.Compute, error)
	Update(ctx context.Context, compute *computev1alpha1.Compute, opts v1.UpdateOptions) (*computev1alpha1.Compute, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, compute *computev1alpha1.Compute, opts v1.UpdateOptions) (*computev1alpha1.Compute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*computev1alpha1.Compute, error)
	List(ctx context.Context, opts v1.ListOptions) (*computev1alpha1.ComputeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *computev1alpha1.Compute, err error)
	Apply(ctx context.Context, compute *applyconfigurationcomputev1alpha1.ComputeApplyConfiguration, opts v1.ApplyOptions) (result *computev1alpha1.Compute, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, compute *applyconfigurationcomputev1alpha1.ComputeApplyConfiguration, opts v1.ApplyOptions) (result *computev1alpha1.Compute, err error)
	ComputeExpansion
}

// computes implements ComputeInterface
type computes struct {
	*gentype.ClientWithListAndApply[*computev1alpha1.Compute, *computev1alpha1.ComputeList, *applyconfigurationcomputev1alpha1.ComputeApplyConfiguration]
}

// newComputes returns a Computes
func newComputes(c *ComputeV1alpha1Client, namespace string) *computes {
	return &computes{
		gentype.NewClientWithListAndApply[*computev1alpha1.Compute, *computev1alpha1.ComputeList, *applyconfigurationcomputev1alpha1.ComputeApplyConfiguration](
			"computes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *computev1alpha1.Compute { return &computev1alpha1.Compute{} },
			func() *computev1alpha1.ComputeList { return &computev1alpha1.ComputeList{} },
		),
	}
}
